### PR TITLE
fix: dealloc BNP storage

### PR DESCRIPTION
**Pull request by pepyakin**

### CODE REVIEW

**Comment by pepyakin** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/346?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#346** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/346?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#345** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/345?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#344** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/344?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#343** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/343?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @pepyakin and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rphmeier — APPROVED** [review]
LGTM

I imagine this is useful when creating and tearing down NOMT repeatedly in the same process?

**Comment by rphmeier** [comment]
### Merge activity

* **Aug 27, 11:09 AM EDT**: @rphmeier started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thrumdev/nomt/346).

**Comment by pepyakin** [comment]
@rphmeier precisely. Showed up when I tried to fuzz this.

**Pull request merged**
