### PR TITLE
opt: preallocate HT file

### PR DESCRIPTION
**Pull request by rphmeier**
This leads to a noticeable improvement in HT write throughput, especially when the file is largely unpopulated.

### CODE REVIEW

**Comment by rphmeier** [comment]
* **#486** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#485** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/485?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rphmeier and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rphmeier** [comment]
* **#486** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#485** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/485?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rphmeier and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by pepyakin — APPROVED** [review]
Minor note: EOPNOTSUPP is set if the fs doesn't support `fallocate(ZERO_RANGE)`. Notable example is ext3. Not sure if anybody cares, because we focus on ext4 at least, but maybe we could call the fallback version or just skip the error printing a warning.

**Comment by pepyakin** [comment]
### Merge activity

* **Oct 18, 9:46 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thrumdev/nomt/485).

**Pull request merged**
